http{
        include mime.types;
        server{
                listen 80;
                root /var/www/doc;
                
                location / {
                    if ($request_uri ~ ^/(.*)\.html(\?|$)) {
                        return 302 /$1;
                    }
                    try_files $uri $uri.html $uri/ =404;
                }
        }
}

events{}
