name: CI pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-26.04  

    env:
      Solution_Name: file-share-solution.sln                        
      Format_Test_Project_Path: format-test/format-test.csproj                
      Server_Core_Test_Project_Path: server-core-test/server-core-test.csproj
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1 #Only need latest commit

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
        
    #Restore before running
    - name: Restore
      run: dotnet restore $Solution_Name

    # Execute all unit tests in the solution
    - name: Execute format test
      run: dotnet test $Format_Test_Project_Path

    - name: Execute server core test
      run: dotnet test $Server_Core_Test_Project_Path
